name: Integration Testing 

on:
  pull_request:
   branches:
    - main
  push :
   branches:
    - main

jobs:
  test:
    runs-on:
      ubuntu-latest


    steps:
    - name: checkout code
      uses : actions/checkout@v2

    - name: Set up Docker build
      uses: docker/setup-buildx-action@v2

    - name : Set up Docker compose
      uses : docker/setup-qemu-action@v2

    - name : Ensure docker compose is available
      run : docker compose version

    - name: Copy envExamle to env
      run : cp ./IntiTesting/.env.example ./IntiTesting/.env

    - name : Run tests 
      run : cd IntiTesting && npm run test:Integration
